apiVersion: v1
kind: Secret
metadata:
  name: collector-secrets
  namespace: collector-shop
  labels:
    app: collector-shop
type: Opaque
stringData:
  JWT_SECRET: "change_me_dev"
  STRIPE_SECRET_KEY: "sk_test_placeholder"
